#!/usr/bin/env bash
# Build script for the Render static site (frontend).
#
# It injects the public Kong gateway URL into config.js so the SPA
# calls the API through Kong instead of its own (static) origin.
#
# On Render, set the static site's Build Command to:  bash build.sh
# and set env var API_BASE_URL=https://kong-gateway-xxxx.onrender.com
set -eu

cd "$(dirname "$0")"

API_BASE_URL="${API_BASE_URL:-}"

if [ -n "$API_BASE_URL" ]; then
  echo "[build.sh] Injecting API_BASE_URL=$API_BASE_URL into config.js"
  cat > config.js <<EOF
/* Auto-generated by build.sh on Render. Do not edit by hand. */
window.__API_BASE__ = "$API_BASE_URL";
EOF
else
  echo "[build.sh] API_BASE_URL not set; leaving config.js at same-origin default"
fi

echo "[build.sh] Frontend build complete."
