services:

  # =========================================================
  # KONG - PUBLIC API GATEWAY
  # =========================================================
  - type: web
    name: kong-gateway
    runtime: docker
    plan: Free
    region: singapore
    dockerfilePath: ./kong/Dockerfile
    dockerContext: ./kong
    autoDeployTrigger: commit

    envVars:
      - key: KONG_DATABASE
        value: "off"

      - key: KONG_DECLARATIVE_CONFIG
        value: /kong/declarative/kong.yml

      - key: PORT
        value: "8000"

      - key: KONG_PROXY_LISTEN
        value: 0.0.0.0:8000

      - key: KONG_ADMIN_LISTEN
        value: "off"

      - key: KONG_PROXY_ACCESS_LOG
        value: /dev/stdout

      - key: KONG_PROXY_ERROR_LOG
        value: /dev/stderr

      # Render private-network host:port of each web service
      - key: AUTH_SERVICE_HOSTPORT
        fromService:
          name: auth-service
          type: web
          property: hostport

      - key: COURSE_SERVICE_HOSTPORT
        fromService:
          name: course-service
          type: web
          property: hostport

      - key: QUIZ_SERVICE_HOSTPORT
        fromService:
          name: quiz-service
          type: web
          property: hostport

      - key: PROGRESS_SERVICE_HOSTPORT
        fromService:
          name: progress-service
          type: web
          property: hostport
      
      - key: API_BASE_URL
        value: "https://kong-gateway-00v6.onrender.com"

      - key: KONG_NGINX_WORKER_PROCESSES
        value: "1"

      - key: KONG_NGINX_WORKER_CONNECTIONS
        value: "256"


  # =========================================================
  # AUTH SERVICE
  # =========================================================
  - type: web
    name: auth-service
    runtime: docker
    plan: Free
    region: singapore
    dockerfilePath: ./auth-service/Dockerfile
    dockerContext: ./auth-service
    autoDeployTrigger: commit

    envVars:
      - key: PORT
        value: "4001"

      - key: DATABASE_URL
        fromDatabase:
          name: dsa-postgres
          property: connectionString

      - key: REDIS_URL
        fromService:
          name: dsa-redis
          type: keyvalue
          property: connectionString

      - key: JWT_SECRET
        generateValue: true


  # =========================================================
  # COURSE SERVICE
  # =========================================================
  - type: web
    name: course-service
    runtime: docker
    plan: Free
    region: singapore
    dockerfilePath: ./course-service/Dockerfile
    dockerContext: ./course-service
    autoDeployTrigger: commit

    envVars:
      - key: PORT
        value: "4002"

      - key: DATABASE_URL
        fromDatabase:
          name: dsa-postgres
          property: connectionString

      - key: REDIS_URL
        fromService:
          name: dsa-redis
          type: keyvalue
          property: connectionString


  # =========================================================
  # QUIZ SERVICE
  # =========================================================
  - type: web
    name: quiz-service
    runtime: docker
    plan: Free
    region: singapore
    dockerfilePath: ./quiz-service/Dockerfile
    dockerContext: ./quiz-service
    autoDeployTrigger: commit

    envVars:
      - key: PORT
        value: "4003"

      - key: DATABASE_URL
        fromDatabase:
          name: dsa-postgres
          property: connectionString

      - key: REDIS_URL
        fromService:
          name: dsa-redis
          type: keyvalue
          property: connectionString


  # =========================================================
  # PROGRESS SERVICE
  # =========================================================
  - type: web
    name: progress-service
    runtime: docker
    plan: Free
    region: singapore
    dockerfilePath: ./progress-service/Dockerfile
    dockerContext: ./progress-service
    autoDeployTrigger: commit

    envVars:
      - key: PORT
        value: "4004"

      - key: DATABASE_URL
        fromDatabase:
          name: dsa-postgres
          property: connectionString

      - key: REDIS_URL
        fromService:
          name: dsa-redis
          type: keyvalue
          property: connectionString

      - key: AUTH_SERVICE_URL
        fromService:
          name: auth-service
          type: web
          property: hostport


  # =========================================================
  # FRONTEND - STATIC SITE
  # =========================================================
  - type: web
    name: dsa-frontend
    runtime: static
    #region: singapore
    staticPublishPath: ./frontend
    autoDeployTrigger: commit
    buildCommand: bash frontend/build.sh

    envVars:
      # Temporary value.
      # Update this after Kong gets its actual Render URL.
      - key: API_BASE_URL
        value: https://kong-gateway-clk8.onrender.com


  # =========================================================
  # REDIS / KEY VALUE
  # =========================================================
  - type: keyvalue
    name: dsa-redis
    plan: Free
    region: singapore
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []


databases:

  # =========================================================
  # POSTGRESQL
  # =========================================================
  - name: dsa-postgres
    plan: Free
    region: singapore
    databaseName: dsalearning
    user: dsauser
    ipAllowList: []